### ISSUE TITLE
release for other distributions

### ISSUE THREAD

**Issue by MoriKen254** [MoriKen254/timed_roslaunch#15]
- ~indigo~
- ~lunar~
- [x] melodic

**Comment by hansbonini** [comment]
- [x] melodic

**Comment by jonaspetersorensen** [comment]
Any idea when you will release it for melodic?

**Comment by akouri-dd** [comment]
It looks like there is a branch already open for Melodic. Can we merge that?

**Comment by MoriKen254** [comment]
Sorry for my late reply.

I just created PR for melodic devel relase.

https://github.com/ros/rosdistro/pull/24531

Plz keep patient until it'll be added to the apt repository.

**Comment by MoriKen254** [comment]
melodic-devel has been released to melodic-devel!

http://packages.ros.org/ros/ubuntu/pool/main/r/ros-melodic-timed-roslaunch/
