### ISSUE TITLE
No built package for Noetic

### ISSUE THREAD

**Issue by bperseghetti** [MoriKen254/timed_roslaunch#17]
@v4hn @forno @MoriKen254 Is there a plan for an apt released build for Noetic?

**Comment by ajithcodesit** [comment]
Any update on when the apt will be released?

**Comment by civerachb-cpr** [comment]
We'd love for this to get released for Noetic too.

**Comment by v4hn** [comment]
ping from me as well. It would be nice to have a noetic release.
