### ISSUE TITLE
Incorrect information in ROS Documentation

### ISSUE THREAD

**Issue by DaPineappleDude** [MoriKen254/timed_roslaunch#8]
While going through the documentation on timed_roslaunch I noticed that there is an error in the **Installation** section, it incorrectly points to a another github repository instead of the timed_roslaunch.

[ROS Documentation link](http://wiki.ros.org/timed_roslaunch)
[Incorrect Repository](https://github.com/CIR-KIT/lower_step_detector)
[Actual Repository]( https://github.com/MoriKen254/timed_roslaunch)

**Comment by MoriKen254** [comment]
@DaPineappleDude 

Thank you for your comment and sorry for late reply.

I updated wiki documentation as you mentioned.

**Comment by DaPineappleDude** [comment]
Thank you for timed_roslaunch, it is a great contribution to the ROS community!

**Comment by MoriKen254** [comment]
Thank you for your kind comment!

I'm currently registering timed_roslaunch into ROS Buildfarm so that you guys can install it via apt install.

https://github.com/ros/rosdistro/pull/19405

**Comment by MoriKen254** [comment]
Now, you can install timed_roslaunch via apt. Here you go!

https://github.com/MoriKen254/timed_roslaunch/blob/kinetic-devel/README.md

**Comment by MoriKen254** [comment]
ok, resolved.
